[build-system]
requires = ['setuptools>=40.8.0']
build-backend = 'setuptools.build_meta'

[project]
name = "georgian-django-payments"
version = "1.0"
description = "Georgian Django Payments"
readme = "README.rst"
requires-python = ">=3.7"
keywords = ["one", "two"]
license = { text = "BSD-3-Clause" }
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
dependencies = [
    'Django >= 3.1',
    "requests",
    'geopayment>=0.6.3',
    'loguru==0.7.0',
]